version: '3.4'

services:
  broker-1:
    ports:
      - 9092:9092
      - 29092:29092

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafka-sqrs-kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker-1:9092"
    networks:
      - backend-net
