version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: kafka-sqrs-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    networks:
      - backend-net

  broker-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-sqrs-broker-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://broker-1:9092,OUTSIDE://broker-1:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:9092,OUTSIDE://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-broker-1:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - backend-net

volumes:
  zookeeper-data:
  kafka-broker-1:

networks:
  backend-net:
